# PARAMETERS
n_epochs: 50000
lr: 0.0005
res_loss_weight: 0.001
lra_alpha: 0.9
batch_size: 64
write_freq: 10000
physical_loss: false
imsize: 65
total_batch_groups: 1
width_plume: 25
length_plume: 25
length_scaling: 3
width_scaling: 1
base_path: /home/daviske/Research/Darus/geothermal-ml
data_path: /home/daviske/Research/Darus/geothermal-ml/data
view_image: True
